sections:
  user-guide:
    title: User Guide
    order: 200
  developer-guide:
    title: Developer Guide
    order: 300

user-guide:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100

    - type: 'pageIds'
      order: 110
      structure: nested

    - type: 'separator'
      title: 'User guide'
      order: 1000

developer-guide:
  menu:
    - type: 'separator'
      title: 'In This Page'
      order: 100

    - type: 'pageIds'
      order: 110
      structure: nested

    - type: 'separator'
      title: 'Developer Guide'
      order: 1000

    - type: 'wiki'
      section: 'Developer Guide'
      order: 1010

wikiPages:
  layout: geopattern2

defaultConfig:
  createPdf: true
