server:
  port: 8092

spring:
  application:
    name: decision-h2
  datasource:
    url: jdbc:h2:mem:decision;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
