application:
  appName: "camundacon2020"
  org: "holunda"
  repository: "${CAMUNDACON_2020_HOME}/repository"

server:
  port: 10110

spring:
  application:
    name: ${application.appName}
  datasource:
    url: jdbc:postgresql://localhost/${application.appName}
    username: ${application.org}
    password: ${application.org}
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    open-in-view: true

camunda:
  bpm:
    admin-user:
      id: admin
      email: admin@localhost
      first-name: Administratus
      last-name: Admintratow
      password: admin

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
