# List all customers
GET http://localhost:10110/customers

###

GET http://localhost:10110/customers/1

###

GET http://localhost:10110/products

###

GET http://localhost:10110/products/1002

###

POST http://localhost:10110/dmn/diagrams/legal_age.dmn

###

GET http://localhost:10110/dmn

###

GET http://localhost:10110/evaluation/isCustomerAdult/1

###

# deploy the live demo example
POST http://localhost:10110/dmn/live-demo

###

GET http://localhost:10110/evaluation/isShipmentAllowed?customerId=2&productId=1002
