example:
  name: "processengine"

server:
  port: 10110

spring:
  application:
    name: camundacon-${example.name}
  datasource:
    url: jdbc:postgresql://localhost/${example.name}
    username: ${example.name}
    password: ${example.name}
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    open-in-view: true

camunda.bpm:
  admin-user:
    id: admin

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
